# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6026f60fa43b7d2714d50048ad8e9e6502cdf272cecb226214f49e18e27e3fe3d316aa466593324a8a3338264db3a06759bfc0d79337c4c57a4825f1766ea1

test:
  secret_key_base: 7e90fc305752f91374f60be198c0dc480f3117477c7a2be04c575be0269e27a5144e336edb81f5020590b5c6fdb7c89fb6fc1b8fa2a5efd3ef947921e133186c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
